server:
  port: 8888
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
      
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: bank
        uri: lb://bank-service
        predicates:
        - Path=/bank/**
      - id: upi
        uri: lb://upi-service
        predicates:
        - Path=/upi/**